### ISSUE TITLE
[ISSUE] Mismatch in ".": Hard links number

### ISSUE THREAD

**Issue by leopku** [Infinidat/fscmp#19]
fscmp /path/to/dirA /path/to/dirB

fscmp 0.2.22

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by gleon99** [comment]
Hi

Thanks for the feedback.

Could you elaborate? What is the output? What are the contents of the dirs? Do you have a reproducing scenario?

**Comment by leopku** [comment]
Just run `fscmp /path/to/dirA /path/to/dirB`

Many files and sub directories in dirA and dirB about 2T capacity with each.

Full backtrace is here

```
thread 'main' panicked at 'assertion failed: path.is_dir()', src/cmp/mod.rs:80:9
stack backtrace:
   0:     0x55a14a001ca5 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55a14a001ca5 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55a14a001ca5 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55a14a001ca5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55a14a02238c - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55a149ffef12 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                               at src/libstd/io/mod.rs:1537
   6:     0x55a14a004340 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55a14a004340 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55a14a004340 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
   9:     0x55a14a00408c - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:217
  10:     0x55a14a004983 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:526
  11:     0x55a149f81d4e - std::panicking::begin_panic::h1a4dd87eb30e4e90
  12:     0x55a149f7478a - fscmp::cmp::EntryInfo::dir::h5676577c25033023
  13:     0x55a149f75959 - fscmp::cmp::FSCmp::dirs::h5c57009e9862363e
  14:     0x55a149f6fb76 - fscmp::main::h23a0f0bb2477971f
  15:     0x55a149f7f793 - std::rt::lang_start::{{closure}}::h285827d47b3ab3fb
  16:     0x55a14a004e23 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                               at src/libstd/rt.rs:52
  17:     0x55a14a004e23 - std::panicking::try::do_call::hac65e71be769a440
                               at src/libstd/panicking.rs:348
  18:     0x55a14a004e23 - std::panicking::try::hd4706e264bcf6712
                               at src/libstd/panicking.rs:325
  19:     0x55a14a004e23 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                               at src/libstd/panic.rs:394
  20:     0x55a14a004e23 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                               at src/libstd/rt.rs:51
  21:     0x55a149f704f2 - main
  22:     0x7efdf6ed2b97 - __libc_start_main
  23:     0x55a149f6632a - _start
  24:                0x0 - <unknown>
```

**Comment by gleon99** [comment]
I was unable to reproduce your issue.
Please notice that the ticket title ("hard links number mismatch") doesn't match the traceback you put above (panic on `is_dir` assert).

Can you provide more info on the contents of each directory? If you have a reproducing scenario, that would be great.
Which `fscmp` version do you use?
